/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MilestoneEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveAndRelease"
      | "cancelBeforeFunding"
      | "client"
      | "creator"
      | "deposit"
      | "getMilestone"
      | "milestoneCount"
      | "releasedAmount"
      | "status"
      | "submitMilestone"
      | "title"
      | "totalAmount"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractCancelled"
      | "ContractCompleted"
      | "FundsDeposited"
      | "MilestoneApproved"
      | "MilestoneSubmitted"
      | "PaymentReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveAndRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBeforeFunding",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "client", values?: undefined): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "milestoneCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releasedAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitMilestone",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "title", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "approveAndRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelBeforeFunding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "client", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "milestoneCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "title", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace ContractCancelledEvent {
  export type InputTuple = [client: AddressLike, refundedAmount: BigNumberish];
  export type OutputTuple = [client: string, refundedAmount: bigint];
  export interface OutputObject {
    client: string;
    refundedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractCompletedEvent {
  export type InputTuple = [escrow: AddressLike, totalReleased: BigNumberish];
  export type OutputTuple = [escrow: string, totalReleased: bigint];
  export interface OutputObject {
    escrow: string;
    totalReleased: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [client: AddressLike, amount: BigNumberish];
  export type OutputTuple = [client: string, amount: bigint];
  export interface OutputObject {
    client: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneApprovedEvent {
  export type InputTuple = [milestoneId: BigNumberish, client: AddressLike];
  export type OutputTuple = [milestoneId: bigint, client: string];
  export interface OutputObject {
    milestoneId: bigint;
    client: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneSubmittedEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    description: string,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    description: string,
    amount: bigint
  ];
  export interface OutputObject {
    milestoneId: bigint;
    description: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    creator: string,
    amount: bigint
  ];
  export interface OutputObject {
    milestoneId: bigint;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MilestoneEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): MilestoneEscrow;
  waitForDeployment(): Promise<this>;

  interface: MilestoneEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveAndRelease: TypedContractMethod<
    [milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelBeforeFunding: TypedContractMethod<[], [void], "nonpayable">;

  client: TypedContractMethod<[], [string], "view">;

  creator: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<[], [void], "nonpayable">;

  getMilestone: TypedContractMethod<
    [milestoneId: BigNumberish],
    [
      [string, bigint, boolean, boolean, boolean] & {
        description: string;
        amount: bigint;
        submitted: boolean;
        approved: boolean;
        released: boolean;
      }
    ],
    "view"
  >;

  milestoneCount: TypedContractMethod<[], [bigint], "view">;

  releasedAmount: TypedContractMethod<[], [bigint], "view">;

  status: TypedContractMethod<[], [bigint], "view">;

  submitMilestone: TypedContractMethod<
    [milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;

  title: TypedContractMethod<[], [string], "view">;

  totalAmount: TypedContractMethod<[], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveAndRelease"
  ): TypedContractMethod<[milestoneId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelBeforeFunding"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "client"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "creator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMilestone"
  ): TypedContractMethod<
    [milestoneId: BigNumberish],
    [
      [string, bigint, boolean, boolean, boolean] & {
        description: string;
        amount: bigint;
        submitted: boolean;
        approved: boolean;
        released: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "milestoneCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "releasedAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitMilestone"
  ): TypedContractMethod<[milestoneId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "title"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ContractCancelled"
  ): TypedContractEvent<
    ContractCancelledEvent.InputTuple,
    ContractCancelledEvent.OutputTuple,
    ContractCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ContractCompleted"
  ): TypedContractEvent<
    ContractCompletedEvent.InputTuple,
    ContractCompletedEvent.OutputTuple,
    ContractCompletedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneApproved"
  ): TypedContractEvent<
    MilestoneApprovedEvent.InputTuple,
    MilestoneApprovedEvent.OutputTuple,
    MilestoneApprovedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneSubmitted"
  ): TypedContractEvent<
    MilestoneSubmittedEvent.InputTuple,
    MilestoneSubmittedEvent.OutputTuple,
    MilestoneSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;

  filters: {
    "ContractCancelled(address,uint256)": TypedContractEvent<
      ContractCancelledEvent.InputTuple,
      ContractCancelledEvent.OutputTuple,
      ContractCancelledEvent.OutputObject
    >;
    ContractCancelled: TypedContractEvent<
      ContractCancelledEvent.InputTuple,
      ContractCancelledEvent.OutputTuple,
      ContractCancelledEvent.OutputObject
    >;

    "ContractCompleted(address,uint256)": TypedContractEvent<
      ContractCompletedEvent.InputTuple,
      ContractCompletedEvent.OutputTuple,
      ContractCompletedEvent.OutputObject
    >;
    ContractCompleted: TypedContractEvent<
      ContractCompletedEvent.InputTuple,
      ContractCompletedEvent.OutputTuple,
      ContractCompletedEvent.OutputObject
    >;

    "FundsDeposited(address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "MilestoneApproved(uint256,address)": TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;
    MilestoneApproved: TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;

    "MilestoneSubmitted(uint256,string,uint256)": TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;
    MilestoneSubmitted: TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;

    "PaymentReleased(uint256,address,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
  };
}
