import Link from "next/link";
import type { CreatorProfile, CreatorVerification } from "@/lib/creator-profile";
import { CreatorVerificationBadges } from "./CreatorVerificationBadges";

export function CreatorPassportSummary({ profile, verification, wallet }: { profile?: CreatorProfile; verification?: CreatorVerification; wallet: string }) {
  if (!profile || !verification) return <section className="rounded-[2rem] border border-arc-line bg-white/80 p-6"><h2 className="text-2xl font-black">Build your Creator Passport</h2><p className="mt-2 max-w-2xl text-sm text-arc-muted">Help advertisers understand your roles, channels, portfolio, availability, and verified Arc settlement history.</p><Link href="/profile/edit" className="mt-5 inline-flex min-h-11 items-center rounded-full bg-arc-ink px-5 py-3 text-sm font-black text-white hover:bg-arc-purple focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-arc-purple">Create profile</Link></section>;
  const completion = [Boolean(profile.displayName), profile.bio.length >= 40, profile.roles.length > 0, profile.languages.length > 0, profile.socialLinks.length > 0 || profile.portfolioItems.length > 0].filter(Boolean).length * 20;
  return <section className="rounded-[2rem] border border-arc-line bg-white/80 p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-arc-ink font-black text-arc-lime">{profile.avatarUrl ? <img src={profile.avatarUrl} alt={`${profile.displayName} avatar`} className="h-full w-full object-cover" /> : profile.displayName.slice(0, 1).toUpperCase()}</div><div className="min-w-0"><p className="text-sm font-bold uppercase tracking-[0.18em] text-arc-muted">Creator Passport</p><h2 className="mt-2 break-words text-2xl font-black">{profile.displayName}</h2><p className="mt-1 break-words text-sm text-arc-muted">{profile.headline || "Creator profile"}</p></div></div><CreatorVerificationBadges verification={verification} /></div><div className="mt-5 flex flex-wrap gap-2">{profile.roles.map((role) => <span key={role} className="rounded-full bg-arc-bg px-3 py-1 text-xs font-black">{role}</span>)}{profile.languages.map((language) => <span key={language} className="rounded-full border border-arc-line px-3 py-1 text-xs font-bold">{language}</span>)}</div><p className="mt-4 text-sm font-bold">Availability: <span className="text-arc-purple">{profile.availability}</span> · Profile completion: <span className="text-arc-purple">{completion}%</span></p><div className="mt-5 flex flex-wrap gap-3"><Link href="/profile/edit" className="inline-flex min-h-11 items-center rounded-full bg-arc-ink px-4 py-2 text-sm font-black text-white hover:bg-arc-purple focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-arc-purple">Edit profile</Link><Link href={`/creators/${wallet}`} className="inline-flex min-h-11 items-center rounded-full border border-arc-line px-4 py-2 text-sm font-black hover:border-arc-purple focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-arc-purple">View public profile</Link></div></section>;
}
