const links = { product: "https://arc-creator-settlement-v0-2.vercel.app", guide: "https://github.com/3624341/arc-korean-build-guide", repo: "https://github.com/3624341/arc-creator-settlement", receipt: "https://arc-creator-settlement-v0-2.vercel.app/receipt/0xdf8a7711dcbe31f07bc1f61d1492d07a0b490f45dd3b0566eaddce5deb6eb856", scan: "https://testnet.arcscan.app/tx/0xdf8a7711dcbe31f07bc1f61d1492d07a0b490f45dd3b0566eaddce5deb6eb856" };
function Link({href, children}:{href:string;children:React.ReactNode}) { return <a href={href} target="_blank" rel="noreferrer">{children} ↗</a>; }
export default function HomePage() { return <main>
  <section className="hero"><p className="network-label">KOREA-BASED ARC BUILDER · TESTNET 5042002</p><h1>Build, ship, and verify on Arc.</h1><p>Open evidence for practical USDC settlement experiments and Korean builder education.</p><div className="actions"><Link href={links.product}>Open Creator Settlement</Link><Link href={links.guide}>Read Korean Build Guide</Link></div></section>
  <section><p className="eyebrow">Projects</p><h2>Two tracks, one builder practice.</h2><div className="grid"><article><h3>Arc Creator Settlement</h3><p>Milestone-based USDC escrow for creators and marketplaces, using Circle Wallet authorization and onchain releases.</p><Link href={links.product}>Live app</Link> · <Link href={links.repo}>Source</Link></article><article><h3>Arc Korean Build Guide</h3><p>A Korean-language field guide for builders learning Arc’s network, wallet, contracts, and deployment workflow.</p><Link href={links.guide}>Open guide</Link></article></div></section>
  <section className="dark"><p className="eyebrow">Verified proof</p><h2>Public facts you can inspect.</h2><div className="stats"><div><strong>5042002</strong><span>Arc Testnet Chain ID</span></div><div><strong>1 USDC</strong><span>Funded demo escrow</span></div><div><strong>0.25 USDC</strong><span>Milestone released</span></div></div><p className="address">Factory: 0x5b90cdfecf1c59596e0b6b9cae448a29c2774e32<br/>Escrow: 0x22De463e9969b8Cef07b151b9cB5D8c5A16D81Df</p><div className="actions"><Link href={links.receipt}>Public receipt</Link><Link href={links.scan}>Verify on ArcScan</Link></div></section>
  <section><p className="eyebrow">Contribution</p><h2>What is shipped today.</h2><div className="grid"><article><h3>Technical</h3><p>Circle Wallet flow · USDC escrow · milestone submit/release · receipt verification · Foundry tests · Arc Doctor checks · network monitor.</p></article><article><h3>Community</h3><p>I’m building from Korea and want to exchange feedback with Arc builders, document findings in Korean, and actively join local Arc activities.</p></article></div></section>
  <section className="roadmap"><p className="eyebrow">Planned</p><h2>Next steps, clearly labelled.</h2><p>Observability and marketplace APIs → Circle Gateway exploration → focused security review → controlled creator pilot → Arc mainnet preparation.</p></section>
</main>; }
