import React from "react";

const links = { product: "https://arc-creator-settlement-v0-2.vercel.app", guide: "https://github.com/3624341/arc-korean-build-guide", repo: "https://github.com/3624341/arc-creator-settlement", receipt: "https://arc-creator-settlement-v0-2.vercel.app/receipt/0xdf8a7711dcbe31f07bc1f61d1492d07a0b490f45dd3b0566eaddce5deb6eb856", scan: "https://testnet.arcscan.app/tx/0xdf8a7711dcbe31f07bc1f61d1492d07a0b490f45dd3b0566eaddce5deb6eb856" };
function Link({ href, children, className = "" }: { href: string; children: React.ReactNode; className?: string }) { return <a className={className} href={href} target="_blank" rel="noreferrer">{children}<span aria-hidden="true"> ↗</span></a>; }
function Arrow() { return <span className="arrow" aria-hidden="true">↗</span>; }

export default function HomePage() { return <main>
  <section className="hero"><div className="hero-copy"><div className="pill"><span className="pulse" /> LIVE ON ARC TESTNET <span className="pill-id">5042002</span></div><h1>A builder’s field notes for <em>Arc.</em></h1><p className="hero-lede">Shipping real USDC flows, documenting what works, and making the path easier for the next builder in Korea.</p><div className="actions"><Link href={links.product} className="button button-lime">Explore the live app <Arrow /></Link><Link href={links.guide} className="button button-dark">Read the Korean guide <Arrow /></Link></div></div><div className="hero-art"><div className="art-top"><span>ARC BUILDER HUB</span><span>01 / 04</span></div><div className="art-title">USDC<br/><strong>settlement</strong><br/>that ships.</div><div className="art-bottom"><span>Creator Settlement</span><span className="mini-line" /></div></div></section>
  <section className="trust"><span>BUILDING IN PUBLIC</span><span>ARC TESTNET</span><span>CIRCLE WALLET</span><span>OPEN SOURCE EVIDENCE</span></section>
  <section className="section"><div className="section-head"><div><p className="eyebrow">01 / Projects</p><h2>Small products.<br/><span>Real onchain proof.</span></h2></div><p className="section-intro">Two connected tracks: one working settlement product, one practical Korean-language guide for builders entering Arc.</p></div><div className="project-grid"><article className="project-card featured"><div className="card-meta"><span>LIVE PRODUCT</span><span className="status-dot">● TESTNET</span></div><h3>Arc Creator<br/><strong>Settlement</strong></h3><p>Programmable USDC milestone payments for creators, freelancers, and marketplaces.</p><div className="card-visual settlement-visual"><div className="visual-bar" /><div className="visual-row"><span>Milestone 01</span><b>0.25 USDC</b></div><div className="visual-row"><span>Contract accepted</span><i>PAID</i></div></div><div className="card-links"><Link href={links.product}>Open live app</Link><Link href={links.repo}>View source</Link></div></article><article className="project-card guide-card"><div className="card-meta"><span>OPEN SOURCE</span><span>한국어</span></div><div className="guide-mark">ARC<br/><b>가이드</b></div><h3>Arc Korean<br/><strong>Build Guide</strong></h3><p>From first wallet to first deployment: a Korean field guide built from hands-on testing.</p><div className="guide-lines"><span>01  Network setup</span><span>02  Circle Wallet</span><span>03  Deploy & verify</span></div><div className="card-links"><Link href={links.guide}>Read the guide</Link></div></article></div></section>
  <section className="proof section"><div className="section-head"><div><p className="eyebrow">02 / Evidence</p><h2>Don’t take my word.<br/><span>Verify it yourself.</span></h2></div><p className="section-intro">Every number below is tied to a public Arc Testnet address or transaction. No screenshots without a trail.</p></div><div className="proof-panel"><div className="proof-stats"><div><b>5042002</b><small>CHAIN ID · ARC TESTNET</small></div><div><b>1.00</b><small>USDC FUNDED ESCROW</small></div><div><b>0.25</b><small>USDC RELEASED</small></div></div><div className="proof-addresses"><div><small>ESCROW FACTORY</small><code>0x5b90…2774e32</code></div><div><small>DEMO ESCROW</small><code>0x22De…D81Df</code></div><div><small>RELEASE TRANSACTION</small><code>0xdf8a…eb856</code></div></div><div className="actions"><Link href={links.receipt} className="button button-lime">Open public receipt <Arrow /></Link><Link href={links.scan} className="button button-outline">Verify on ArcScan <Arrow /></Link></div></div></section>
  <section className="section contribution"><p className="eyebrow">03 / How I build</p><div className="contribution-grid"><div><h2>Useful beats<br/><span>theoretical.</span></h2><p className="section-intro">I’m building from Korea, sharing the implementation details, and turning each failed deployment into a clearer checklist.</p></div><div className="capability-list"><div><strong>01</strong><span>Circle Wallet authorization</span><small>Shipped · user-owned wallet flow</small></div><div><strong>02</strong><span>Milestone escrow & release</span><small>Shipped · USDC onchain state</small></div><div><strong>03</strong><span>Receipt verification</span><small>Shipped · ArcScan-linked evidence</small></div><div><strong>04</strong><span>Korean builder documentation</span><small>Shipped · open source guide</small></div></div></div></section>
  <section className="roadmap section"><div className="roadmap-top"><div><p className="eyebrow">04 / Next</p><h2>Keep shipping.<br/><span>Keep learning.</span></h2></div><div className="planned-badge">PLANNED ROADMAP <Arrow /></div></div><div className="roadmap-items"><div><b>02</b><span>Observability & marketplace APIs</span><small>Next build cycle</small></div><div><b>03</b><span>Circle Gateway exploration</span><small>After milestone 2</small></div><div><b>04</b><span>Security review & controlled pilot</span><small>After milestone 3</small></div></div></section>
  <section className="closing"><p className="eyebrow">BUILT IN SEOUL · OPEN TO FEEDBACK</p><h2>Building on Arc?<br/><em>Let’s compare notes.</em></h2><div className="actions"><Link href={links.repo} className="button button-dark">Visit GitHub <Arrow /></Link><Link href={links.guide} className="button button-lime">Start with the guide <Arrow /></Link></div></section><footer><span>ARC BUILDER HUB</span><span>CREATOR SETTLEMENT · 2026</span></footer>
</main>; }
